export { P, HTW, HTH, COLS, ROWS, WW, WH, FURN, INTERACTIVES, MUSIC_OBJ, DEFAULT_CAM, dayPhase } from "../room-art/room-config";
export { buildBackground, tourDoorBounds, socialDoorBounds } from "../room-art/room-background";
export { buildFurniture } from "../room-art/room-furniture";
export { buildBoard } from "../room-art/board";
export { drawMonitorScene } from "../room-art/room-monitor.js";
export { buildAvatar, DEFAULT_LOOK } from "../avatar/avatar-sprite-renderer";
export { buildArcadeBackground, arcadeDoorBounds } from "../arcade-room/ArcadeBackground";
export { buildArcadeFurniture } from "../arcade-room/ArcadeSprites";
export { FURN_ARCADE, INTERACTIVES_ARCADE, ARC_ENTRY_TILE, TOUR_ENTRY_TILE, ARC_DEFAULT_CAM } from "../arcade-room/arcade-config";
export { buildPiazzaBackground, piazzaDoorBounds } from "../social-room/PiazzaBackground";
export { buildPiazzaFurniture } from "../social-room/PiazzaSprites";
export { FURN_PIAZZA, INTERACTIVES_PIAZZA, PIAZZA_ENTRY_TILE, PIAZZA_DEFAULT_CAM } from "../social-room/piazza-config";
export { syncRemotePlayers, tickRemotePlayers, drawRemotePlayer } from "../social-room/piazza-remote-players";
export { getFxFlags } from "../quality-config";
export { createFrameLimiter } from "../frame-limiter";
export { shouldApplyLocalPosition } from "./api-bridge.js";
export { createWorldInputBindings } from "./input.js";
export { createWorldNavigation, getInteractionModalId } from "./navigation.js";
export { fitWorldScale } from "./math.js";
export { normalizeStats } from "./config.js";
export { ASSO_BODY_COL, ASSO_EYE_CELLS, ASSO_GH, ASSO_GRID, ASSO_GW } from "../../lib/asso-pixel";
export { buildCat, buildDog } from "../world-client/world-pets";
export { makeAudio } from "../world-client/world-audio";
export { EGG_LINES, BAN_LINES, WEEK_LINES, MOCK_TOURNAMENT_NAMES, CREDIT_REWARD_NICE, mockCreditReward, slotCreditValue, formatCredits, CREDITS_REWARD_CARD, EBARTEX_CREDITO_URL, EB_LINK_ORANGE, SHADOW_LINES, AFK_LINES, MTG_CARDS, MTG_TEMPLATES } from "../world-client/world-content";
export { clamp, lerp, easeInOutCubic, easeOutQuad, easeOutCubic, easeInCubic, easeOutBack, tileTop, worldToTile, inGrid, tkey, shade, hexA, findPath, cmpDepth, mkCanvas, isoVec, quadFill, isoBox, mkSprite, outlined, makeSil, wallL, wallR, wallFar } from "../world-client/world-geometry";
export { TUT_STEPS, TUT_CHAR_MS, tutPauseMs, tutTypingMs, tutReadMs, tutCaptionMs, tutCaptionSec, tutHoldSec, tutUiHoldSec, TUT_OUTRO, TUT_BRAND, TUT_WAIT, TUT_UI_HOTSPOTS, tutEstimatedStepSec, tutTotalDurationSec, formatTutDurationLabel, TUT_DURATION_LABEL } from "../world-client/tutorial-timing";
export const SPEED = 3.4;
export const ARCADE_GAME_IDS = new Set(["arcade1", "arcade2", "arcade3", "kakegurui"]);
export const ICON_POS = { pc: { x: 196, y: 148 }, decks: { x: 464, y: 284 }, board: { x: 474, y: 106 } };
