export const TUTORIAL_CSS = [
  /* — tutorial guidato: banner che diventa cartello grande (intro/outro) — */
  ".irg-tut{position:absolute;top:64px;left:50%;transform:translateX(-50%);z-index:60;",
  "width:min(700px,93vw);pointer-events:none;animation:irgTutIn .4s cubic-bezier(.34,1.45,.64,1);",
  "transition:top .6s cubic-bezier(.4,0,.2,1),width .55s cubic-bezier(.4,0,.2,1);}",
  ".irg-tut-bar{pointer-events:auto;display:flex;align-items:center;gap:14px;",
  "background:linear-gradient(180deg,rgba(38,26,15,.97),rgba(22,15,9,.98));",
  "border:1px solid rgba(255,138,42,.42);border-radius:16px;padding:13px 16px;",
  "box-shadow:0 16px 44px rgba(0,0,0,.5),0 0 22px rgba(255,120,20,.12),inset 0 1px 0 rgba(255,180,110,.12);backdrop-filter:blur(7px);-webkit-backdrop-filter:blur(7px);",
  "transition:padding .5s ease,border-radius .5s ease;}",
  ".irg-tut-ghost{flex:0 0 auto;width:46px;height:50px;display:flex;align-items:flex-end;justify-content:center;",
  "transition:width .4s ease,height .4s ease;animation:irgGhostBob 3.2s ease-in-out infinite;",
  "filter:drop-shadow(0 5px 10px rgba(255,110,20,.4));}",
  ".irg-tut-ghost svg{width:100%;height:100%;overflow:visible;}",
  ".irg-ghost-body{fill:#fff7ef;stroke:rgba(255,150,60,.55);stroke-width:1.2;}",
  ".irg-ghost-eye{fill:#3a2a16;}",
  ".irg-ghost-blush{fill:rgba(255,140,60,.5);}",
  ".irg-tut-eyes{transform-origin:8.5px 7.5px;animation:irgGhostBlink 4.4s ease-in-out infinite;}",
  ".irg-tut-text{position:relative;flex:1 1 auto;color:#fdf3e8;font-size:15px;font-weight:600;line-height:1.45;",
  "transition:font-size .45s ease;}",
  ".irg-tut-reserve{visibility:hidden;display:block;white-space:pre-line;}",
  ".irg-tut-typed{position:absolute;inset:0;display:block;}",
  ".irg-tut-word{display:inline-block;white-space:nowrap;}",
  ".irg-tut-sp{white-space:pre;}",
  ".irg-tut-ch{display:inline-block;white-space:pre;animation:irgChIn .22s ease both;}",
  ".irg-tut-brand{color:#FF7300;text-shadow:0 0 12px rgba(255,115,0,.42);}",
  ".irg-tut-intro .irg-tut-brand,.irg-tut-final .irg-tut-brand{text-shadow:0 0 18px rgba(255,115,0,.52);}",
  ".irg-tut-pill{display:inline-block;margin-right:.4em;padding:.2em .72em;border-radius:999px;vertical-align:baseline;",
  "background:linear-gradient(180deg,rgba(255,154,61,.38),rgba(255,115,0,.24));",
  "border:1px solid rgba(255,167,80,.52);box-shadow:0 2px 12px rgba(255,115,0,.22),inset 0 1px 0 rgba(255,255,255,.14);",
  "font-weight:800;font-size:.9em;letter-spacing:.04em;color:#fff3e4;white-space:nowrap;}",
  "@keyframes irgChIn{from{opacity:0;transform:translateY(.16em) scale(.94);filter:blur(.5px)}to{opacity:1;transform:none;filter:none}}",
  ".irg-tut-caret{display:inline-block;width:2px;height:1.05em;margin-left:2px;vertical-align:-2px;",
  "background:#ffb060;border-radius:1px;animation:irgCaret .8s steps(1) infinite;}",
  ".irg-tut-skip{flex:0 0 auto;cursor:pointer;border:1px solid rgba(255,255,255,.22);",
  "background:rgba(255,255,255,.06);color:#cfd6f5;border-radius:9px;padding:9px 13px;font-size:12.5px;",
  "font-weight:700;transition:background-color .18s,color .18s,border-color .18s,transform .12s;white-space:nowrap;}",
  ".irg-tut-skip:hover{background:rgba(255,115,0,.2);border-color:rgba(255,115,0,.45);color:#fff;transform:scale(1.04);}",
  ".irg-tut-skip:active{transform:scale(.96);}",
  ".irg-tut-side{flex:0 0 auto;display:flex;flex-direction:column;align-items:center;gap:5px;}",
  ".irg-tut-dur{font-size:10.5px;font-weight:600;line-height:1.2;color:rgba(207,214,245,.62);letter-spacing:.03em;white-space:nowrap;}",
  ".irg-tut-dur-intro{margin-top:2px;font-size:13px;color:rgba(253,243,232,.58);}",
  /* stato grande: cartello al centro (intro e outro) */
  ".irg-tut-intro{top:36%;width:min(780px,94vw);}",
  ".irg-tut-intro .irg-tut-bar{flex-direction:column;text-align:center;gap:17px;padding:28px 30px;",
  "border-radius:24px;border-color:rgba(129,140,248,.48);box-shadow:0 30px 80px rgba(0,0,0,.62);}",
  ".irg-tut-intro .irg-tut-ghost{width:80px;height:88px;}",
  ".irg-tut-intro .irg-tut-text{font-size:24px;font-weight:800;line-height:1.34;min-height:2.4em;}",
  ".irg-tut-intro .irg-tut-skip{display:none;}",
  /* outro: cartello finale con i bottoni di scelta */
  ".irg-tut-final{top:30%;}",
  ".irg-tut-actions{display:flex;flex-direction:column;align-items:center;gap:13px;width:100%;margin-top:2px;}",
  ".irg-tut-repeat{display:flex;align-items:center;gap:10px;flex-wrap:wrap;justify-content:center;}",
  ".irg-tut-q{font-size:15px;font-weight:700;color:#cfd6f5;}",
  ".irg-tut-btn{cursor:pointer;border-radius:11px;padding:11px 20px;font-size:14.5px;font-weight:800;",
  "font-family:'Segoe UI',system-ui,sans-serif;border:1px solid rgba(255,255,255,.2);background:rgba(255,255,255,.07);",
  "color:#eef2ff;transition:background-color .16s,border-color .16s,transform .1s,box-shadow .16s;}",
  ".irg-tut-btn:hover{transform:translateY(-2px);box-shadow:0 10px 26px rgba(0,0,0,.45);}",
  ".irg-tut-btn:active{transform:translateY(0) scale(.97);}",
  ".irg-tut-yes{background:linear-gradient(180deg,#2fe08a,#10b46a);color:#06241a;border-color:rgba(255,255,255,.45);}",
  ".irg-tut-yes:hover{border-color:#7dffc2;}",
  ".irg-tut-no{min-width:62px;}",
  ".irg-tut-no:hover{border-color:rgba(255,120,120,.6);background:rgba(255,90,90,.16);}",
  ".irg-tut-simple{background:linear-gradient(180deg,#ff9a3d,#ff7300);color:#fff;border-color:rgba(255,255,255,.4);",
  "box-shadow:0 8px 22px rgba(255,115,0,.35);}",
  ".irg-tut-simple:hover{box-shadow:0 12px 30px rgba(255,115,0,.5);}",
  "@keyframes irgWave{0%,60%,100%{transform:rotate(0)}10%{transform:rotate(16deg)}20%{transform:rotate(-8deg)}30%{transform:rotate(16deg)}40%{transform:rotate(-4deg)}50%{transform:rotate(12deg)}}",
  "@keyframes irgGhostBob{0%,100%{transform:translateY(0) rotate(-2.5deg)}50%{transform:translateY(-5px) rotate(2.5deg)}}",
  "@keyframes irgGhostBlink{0%,92%,100%{transform:scaleY(1)}96%{transform:scaleY(.12)}}",
  "@keyframes irgCaret{0%{opacity:1}50%{opacity:0}}",
  "@keyframes irgTutIn{from{opacity:0;transform:translateX(-50%) translateY(-10px) scale(.96)}",
  "to{opacity:1;transform:translateX(-50%) translateY(0) scale(1)}}",
  "@media (max-width:560px){.irg-tut{top:54px;}.irg-tut-text{font-size:13.5px;}.irg-tut-ghost{width:40px;height:44px;}.irg-tut-intro .irg-tut-ghost{width:66px;height:74px;}",
  ".irg-tut-intro{top:26%;}.irg-tut-intro .irg-tut-text{font-size:19px;}",
  ".irg-tut-btn{font-size:13px;padding:10px 16px;}.irg-tut-q{font-size:13.5px;}}",
  /* — Asso persistente (helper post-tutorial), ancorato a destra fuori dalla scena — */
  ".irg-helper{position:fixed;right:14px;top:50%;transform:translateY(-50%);z-index:60;cursor:pointer;",
  "display:flex;align-items:center;justify-content:flex-end;-webkit-tap-highlight-color:transparent;",
  "animation:irgHelperIn .5s cubic-bezier(.34,1.56,.64,1) both;}",
  ".irg-helper:focus-visible{outline:2px solid rgba(255,138,42,.85);outline-offset:4px;border-radius:12px;}",
  ".irg-helper-asso{width:58px;height:72px;display:block;pointer-events:none;",
  "filter:drop-shadow(0 6px 12px rgba(255,110,20,.42));animation:irgGhostBob 3.2s ease-in-out infinite;",
  "transition:transform .18s ease;}",
  ".irg-helper:hover .irg-helper-asso{transform:scale(1.07);}",
  ".irg-helper:active .irg-helper-asso{transform:scale(.94);}",
  ".irg-helper-asso svg{width:100%;height:100%;overflow:visible;display:block;}",
  ".irg-helper-talking .irg-helper-asso{animation-duration:1.6s;}",
  ".irg-helper-bubble{position:absolute;right:100%;margin-right:12px;bottom:50%;transform:translateY(50%);",
  "max-width:212px;width:max-content;text-align:left;color:#fdf3e8;font-size:13px;font-weight:600;line-height:1.4;",
  "background:linear-gradient(180deg,rgba(38,28,20,.97),rgba(26,19,13,.97));",
  "border:1px solid rgba(255,150,60,.45);border-radius:13px;padding:10px 13px;",
  "box-shadow:0 12px 30px rgba(0,0,0,.5),0 0 18px rgba(255,120,20,.14);",
  "animation:irgHelperBubbleIn .26s cubic-bezier(.34,1.56,.64,1) both;}",
  ".irg-helper-bubble::after{content:'';position:absolute;left:100%;top:50%;transform:translateY(-50%);",
  "border:7px solid transparent;border-left-color:rgba(255,150,60,.55);}",
  "@keyframes irgHelperIn{from{opacity:0;transform:translateY(-50%) translateX(22px) scale(.8)}to{opacity:1;transform:translateY(-50%) translateX(0) scale(1)}}",
  "@keyframes irgHelperBubbleIn{from{opacity:0;transform:translateY(50%) translateX(8px) scale(.92)}to{opacity:1;transform:translateY(50%) translateX(0) scale(1)}}",
  "@media (max-width:560px){.irg-helper{right:8px;}.irg-helper-asso{width:48px;height:60px;}.irg-helper-bubble{max-width:160px;font-size:12px;}}",
  /* — punti caldi del tutorial: cerchio pulsante + cartello con freccia — */
  ".irg-spots{position:absolute;inset:0;z-index:50;pointer-events:none;}",
  ".irg-spot{position:absolute;animation:irgSpotPop .42s cubic-bezier(.34,1.45,.64,1) both;}",
  ".irg-spot-ring{position:absolute;inset:-6px;border:2.5px solid #ffcf45;border-radius:13px;",
  "box-shadow:0 0 0 3px rgba(255,207,69,.16),0 0 18px rgba(255,160,40,.5);",
  "animation:irgSpotPulse 1.5s ease-in-out infinite;}",
  /* il cartello usa transform per centrarsi sul lato: l'entrata è solo in
     opacità così non entra in conflitto col posizionamento */
  ".irg-spot-label{position:absolute;width:max-content;max-width:220px;text-align:center;",
  "background:linear-gradient(180deg,#ffd45a,#ff9d2e);color:#3a1f00;font-size:12px;font-weight:800;",
  "line-height:1.32;letter-spacing:.2px;padding:6px 11px;border-radius:10px;",
  "box-shadow:0 9px 24px rgba(0,0,0,.4),inset 0 1px 0 rgba(255,255,255,.4);",
  "opacity:0;animation:irgSpotLabel .4s ease .12s forwards;}",
  ".irg-spot-label:after{content:'';position:absolute;width:9px;height:9px;background:inherit;",
  "transform:rotate(45deg);}",
  /* lato cartello + freccia */
  ".irg-spot-bottom .irg-spot-label{top:calc(100% + 14px);left:50%;transform:translateX(-50%);}",
  ".irg-spot-bottom .irg-spot-label:after{top:-4px;left:50%;margin-left:-4px;}",
  ".irg-spot-top .irg-spot-label{bottom:calc(100% + 14px);left:50%;transform:translateX(-50%);}",
  ".irg-spot-top .irg-spot-label:after{bottom:-4px;left:50%;margin-left:-4px;}",
  ".irg-spot-left .irg-spot-label{right:calc(100% + 14px);top:50%;transform:translateY(-50%);}",
  ".irg-spot-left .irg-spot-label:after{right:-4px;top:50%;margin-top:-4px;}",
  ".irg-spot-right .irg-spot-label{left:calc(100% + 14px);top:50%;transform:translateY(-50%);}",
  ".irg-spot-right .irg-spot-label:after{left:-4px;top:50%;margin-top:-4px;}",
  "@keyframes irgSpotPop{from{opacity:0;transform:scale(.8)}to{opacity:1;transform:scale(1)}}",
  "@keyframes irgSpotLabel{to{opacity:1}}",
  "@keyframes irgSpotPulse{0%,100%{box-shadow:0 0 0 3px rgba(255,207,69,.14),0 0 14px rgba(255,160,40,.38);border-color:#ffc636}",
  "50%{box-shadow:0 0 0 7px rgba(255,207,69,.05),0 0 28px rgba(255,160,40,.7);border-color:#ffe289}}",
  /* zoom leggero sull'elemento cerchiato nella legenda del tutorial */
  ".irg-spot-target{position:relative;z-index:2;transform-origin:center center;transform:scale(1.05);",
  "transition:transform .42s cubic-bezier(.34,1.45,.64,1);transition-delay:var(--irg-spot-delay,0s);}",
  "@media (prefers-reduced-motion:reduce){.irg-spot-ring{animation:none}.irg-spot-target{transition:none;transform:scale(1.03)}}",
  /* — backdrop e modale — */
  ".irg-backdrop{position:absolute;inset:0;z-index:30;display:flex;align-items:center;justify-content:center;",
  "background:rgba(10,12,22,.46);backdrop-filter:blur(2.5px) saturate(.92);animation:irgFade .25s ease;padding:18px;}",
  ".irg-backdrop.irg-closing{animation:irgFadeOut .16s ease forwards;}",
  "@keyframes irgFade{from{opacity:0}to{opacity:1}}",
  "@keyframes irgFadeOut{from{opacity:1}to{opacity:0}}",
  ".irg-modal{position:relative;max-height:92%;overflow:auto;overscroll-behavior:contain;border-radius:14px;",
  "animation:irgIn .3s cubic-bezier(.34,1.45,.64,1);box-shadow:0 24px 70px rgba(0,0,0,.55);}",
  ".irg-closing .irg-modal{animation:irgOut .16s ease forwards;}",
  "@keyframes irgIn{from{opacity:0;transform:scale(.9) translateY(14px)}to{opacity:1;transform:scale(1) translateY(0)}}",
  "@keyframes irgOut{from{opacity:1;transform:scale(1)}to{opacity:0;transform:scale(.94) translateY(8px)}}",
  ".irg-x{position:absolute;top:10px;right:10px;z-index:5;width:34px;height:34px;border:0;border-radius:10px;",
  "background:rgba(255,255,255,.08);color:#ffe9b0;font-size:16px;line-height:1;cursor:pointer;",
  "border:1px solid rgba(242,185,75,.35);",
  "transition:transform .15s ease,background .15s ease,border-color .15s ease,color .15s ease;}",
  ".irg-x:hover{background:rgba(255,115,0,.2);color:#fff;border-color:#FF7300;transform:rotate(8deg) scale(1.08);}",
  ".irg-esc{font-family:'Press Start 2P','Courier New',monospace;font-size:8px;opacity:.6;margin-left:8px;letter-spacing:.5px;}",
  ".irg-mtitle{font-family:'Press Start 2P','Courier New',monospace;font-size:13px;display:flex;align-items:center;gap:10px;}",
  /* — scrollbar — */
  ".irg-modal ::-webkit-scrollbar,.irg-modal::-webkit-scrollbar{width:9px;height:9px;}",
  ".irg-modal ::-webkit-scrollbar-thumb,.irg-modal::-webkit-scrollbar-thumb{background:linear-gradient(180deg,rgba(242,185,75,.5),rgba(242,185,75,.25));border-radius:8px;}",
  ".irg-modal ::-webkit-scrollbar-track,.irg-modal::-webkit-scrollbar-track{background:rgba(0,0,0,.2);}",
  "@media (max-width:600px){",
  ".irg-mtitle{font-size:11px;}",
  "}",
  /* — modalità leggera — */
  ".irg-quality-low .irg-backdrop{",
  "backdrop-filter:none;-webkit-backdrop-filter:none;background:rgba(10,12,22,.94);}",
  ".irg-quality-low .irg-canvas{image-rendering:pixelated;}",
  ".irg-quality-low .irg-chip,.irg-quality-low .irg-controls,.irg-quality-low .irg-key{backdrop-filter:none;-webkit-backdrop-filter:none;}",
  ".irg-quality-low .irg-hint,.irg-quality-low .irg-helper-asso,.irg-quality-low .irg-tut-ghost,.irg-quality-low .irg-tut-eyes,.irg-quality-low .irg-tut-caret{animation:none;}",
].join("\n");
